feat: non-contiguous source range
sinui0/spansy pull request #11
Opened 2024-01-28 21:50 UTC by sinui0

This PR switches to using `RangeSet` for `Span` which prepares to support parsing spans from non-contiguous source data. This will be required to support parsing HTTP bodies with a `chunked` transfer encoding.

~~Let's hold off on merging this until we address https://github.com/tlsnotary/tlsn-utils/issues/14 and can pin the main branch.~~

2024-01-30 21:33 UTC, sinui0 commented
@themighty1 @th4s ready for review. We can transplant this to `tlsn-utils` after we get some stuff merged in

2024-01-31 11:01 UTC, th4s approved these changes
:+1:

2024-02-01 07:10 UTC, themighty1 requested changes

2024-02-01 07:10 UTC, themighty1 commented on src/http/span.rs
> +    let header_range = name_range.start..value_range.end + 2;
` header_range` must also account for any optional trailing whitespaces that may exist between the value and CRLF.

2024-02-02 02:23 UTC, sinui0 commented on src/http/span.rs
> +    let header_range = name_range.start..value_range.end + 2;
good catch, fixed.

2024-02-02 05:52 UTC, themighty1 approved these changes

2024-02-02 05:53 UTC, merged