feat: subspans
sinui0/spansy pull request #12
Opened 2024-01-30 21:36 UTC by sinui0

This PR builds on #11 and adds the "subspan" methods we use in `tlsn-formats`.

2024-01-31 11:29 UTC, th4s approved these changes
:+1:

2024-01-31 11:29 UTC, th4s commented on src/http/types.rs
> +    /// Returns the indices of the request excluding the path, headers and body.
```suggestion
    /// Returns the indices of the request excluding the request line, headers and body.
```

2024-01-31 11:29 UTC, th4s commented on src/json/types.rs
> +    }
What about spaces and line breaks? Do they belong to the value then?

2024-02-01 08:10 UTC, themighty1 requested changes

2024-02-01 08:10 UTC, themighty1 commented on src/http/types.rs
> +    /// Returns the indices of the header excluding the value.
Since `header` is a `field-line` in the RFC and `field-line` is defined as
`  field-line   = field-name ":" OWS field-value OWS`
this comment should add that CRLF **is** included

Also worth changing the description of `pub struct Header {`
to read /// An HTTP header including the trailing CRLF.

2024-02-01 08:10 UTC, themighty1 commented on src/http/types.rs
> +    pub fn without_path(&self) -> RangeSet<usize> {
While we are at it: do we really want to store in inside the `RequestLine` just the `path`, i.e. "/about-us" or do we want to store what the RFC calls `request-target` which can be a URI e.g. `https://www.example.com/path/to/resource?query=example` ? I think the latter, no ?

2024-02-01 08:10 UTC, themighty1 commented on src/http/types.rs
Let's change the comment for `RequestLine` to /// An HTTP request line including the trailing CRLF.

2024-02-01 08:10 UTC, themighty1 commented on src/json/types.rs
> +    pub fn without_values(&self) -> RangeSet<usize> {
maybe `without_brackets` is a more precise name?

2024-02-01 08:10 UTC, themighty1 commented on src/json/types.rs
> +/// An object value.
```suggestion
/// A JSON object value.
```

2024-02-02 02:30 UTC, sinui0 commented on src/json/types.rs
> +    pub fn without_values(&self) -> RangeSet<usize> {
This returns only the brackets, ie excluding the values

2024-02-02 02:32 UTC, sinui0 commented on src/json/types.rs
> +    }
The json parser will only capture the opening and closing brackets and everything in between. This excludes everything other than the brackets.

2024-02-02 02:33 UTC, sinui0 commented on src/http/types.rs
> +    /// Returns the indices of the request excluding the path, headers and body.
Good catch, I actually want to exclude only the path here.

2024-02-02 02:40 UTC, sinui0 commented on src/http/types.rs
> +    pub fn without_path(&self) -> RangeSet<usize> {
I just borrowed the naming from `httparse`, the `path` span does include query params, or more specifically, everything inbetween the method and version fields.

2024-02-05 06:04 UTC, themighty1 commented on src/http/types.rs
> +    pub fn without_path(&self) -> RangeSet<usize> {
I see. Maybe we can use a name in line with the RFC, like e.g. `target`

2024-02-05 06:11 UTC, themighty1 requested changes

2024-02-05 06:11 UTC, themighty1 commented on src/json/types.rs
> +    /// Returns the indices of the array, excluding the values.
```suggestion
    /// Returns the indices of the array, excluding the values and the separators.
```

2024-02-05 06:15 UTC, sinui0 commented on src/http/types.rs
> +    pub fn without_path(&self) -> RangeSet<usize> {
Sure we can rename it. Looking at [`RFC 2616`](https://www.rfc-editor.org/rfc/rfc2616#section-5.1) it says that field is called the `Request-URI`

2024-02-05 06:15 UTC, sinui0 commented on src/http/types.rs
> +    pub fn without_path(&self) -> RangeSet<usize> {
Ah, thats the old RFC, nvm

2024-02-05 07:09 UTC, themighty1 approved these changes

2024-02-05 07:26 UTC, merged