fix: fix offset, forbid trailing chars in json, require utf8 in Span<…
sinui0/spansy pull request #6
Opened 2023-10-27 12:39 UTC by themighty1

This PR:
- fixes an offset in http parser and adds tests for that
- prohibits trailing characters when parsing a json value
- checks that Span<str> is built from a utf8 string

2023-10-27 12:40 UTC, themighty1 commented
I can't request reviews on this repo the normal way, so pinging @sinui0 @th4s for review

2023-10-27 16:22 UTC, sinui0 reviewed
Lgtm, 1 comment

2023-10-30 07:22 UTC, themighty1 commented on src/lib.rs
> +        Span::new_str(src, range)
oh, right. I will revert this to how it was.

2023-10-30 09:49 UTC, th4s approved these changes
:+1:

2023-10-30 17:49 UTC, sinui0 approved these changes

2023-10-30 17:55 UTC, sinui0 requested changes

2023-10-31 10:30 UTC, merged